- kernel/fbsd/ena/ena.c
Lack of this lock was causing crash if down was called in
parallel with the initialization routine.
> fbsd/ena: Add missing lock upon initialization of the interface

- kernel/fbsd/ena/ena.c
ena_alloc_rx_mbuf() will return positive error code
on failure. Act accordingly.
Submitted by: Krishna Yenduri <kyenduri@brkt.com>
> fbsd/ena: Fix error check for Rx mbuf allocation

- kernel/linux/ena/kcompat.h
`devm_ioremap_wc` is included in the Ubuntu kernel as of 3.13.0-126
> Fix ubuntu kernel compatibility

- kernel/linux/rpm/Makefile
Allow use of `make -C /usr/src/ena-${ENA_VER}/kernel/linux/rpm rpm`
> Remove chdir to $(TOPDIR) for make -C invocation

- kernel/fbsd/ena/ena_com/ena_plat.h
WARN_ON was only called from ENA_ASSERT macro and it was doing
almost the same thing as ENA_ASSERT. Instead of modyfing it, it is
removed.
This fix allows gcc compilation of the driver with standard
warning flags.
Submitted by: Ryan Libby <rlibby@gmail.com>
> fbsd/ena: remove unused statement from platform code

- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_com/ena_plat.h
* Remove NULL checks for malloc with M_WAITOK.
* Do not check conditions explicitely for bool variables.
* Remove ENA_NAME_MAX_LEN.
* Remove single extra leading whitespace.
* Expand goto if retrieving RX mbuf fails.
* Fix error handling routine by assigning value to free_rx_ids instead
of tx.
* Change M_NOWAIT to M_WAITOK on taskqueue_create_fast for alignment.
* Minor style fixes.
* Fix typo in printout.
* Cast field of the mbuf csum_flags to fix compilation error with newest
FreeBSD kernel (from r325506).
> Apply fixes from community review of the ENA FreeBSD

- userspace/dpdk/16.04/0002-net-ena-TX-L4-offload-flags-should-not-be-set-in-RX-.patch
- userspace/dpdk/16.11/0006-net-ena-TX-L4-offload-flags-should-not-be-set-in-RX-.patch
- userspace/dpdk/17.02/0007-net-ena-TX-L4-offload-flags-should-not-be-set-in-RX-.patch
- userspace/dpdk/17.05/0003-net-ena-TX-L4-offload-flags-should-not-be-set-in-RX-.patch
- userspace/dpdk/17.08/0001-net-ena-TX-L4-offload-flags-should-not-be-set-in-RX-.patch
- userspace/dpdk/17.11/0001-net-ena-TX-L4-offload-flags-should-not-be-set-in-RX-.patch
Information about received packet type detected by NIC should be stored
in packet_type field of rte_mbuf. TX L4 offload flags should not be set
in RX path.
Only fields that could be set in of_flags during packet receiving are
information if L4 and L3 checksum is correct.
The patch for the given issue had been provided for all versions.
> dpdk/ena: fix RX mbuf flags settings

- userspace/dpdk/RELEASENOTES.md
The release notes were released for versions 18.11 due to release and
upcoming stable version 16.11.9.
> dpdk/ena: update release notes for the driver

- kernel/fbsd/ena/Makefile
- kernel/fbsd/ena/README
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_com/ena_com.c
- kernel/fbsd/ena/ena_com/ena_com.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_admin_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_common_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_eth_io_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_gen_info.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_regs_defs.h
- kernel/fbsd/ena/ena_com/ena_eth_com.c
- kernel/fbsd/ena/ena_com/ena_eth_com.h
- kernel/fbsd/ena/ena_com/ena_plat.h
- kernel/fbsd/ena/ena_sysctl.c
- kernel/fbsd/ena/ena_sysctl.h
Changes since last release (v0.8.1)
* LLQ (Low Latency Queue) feature was added. New placement policy
enables storing Tx descriptor rings and packet headers in the device
memory. LLQs improve average and tail latencies. As part of LLQs
enablement new admin capability was defined, device memory was mapped
as write-combined and the transmit processing flow was updated.
* Rx checksum offloads can now be used on some of the HW.
* Optimization of the locks on both Tx and Rx paths. Rx locks were
removed and Tx locks were optimized by adding queue management (stop
and start).
* Additional Tx doorbells checks were added - supported only by some of
the hardware.
**Bug Fixes**
* Suppress excessive error printouts in Tx hot path.
* Fix validation of the Rx OOO completion.
* Prevent …
> fbsd/ena: update ENA FreeBSD driver to version 2.0.0

- kernel/linux/efa/Makefile
- kernel/linux/ena/Makefile
This resolves the warning:
'make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.'
> Allow parallel build.

- kernel/fbsd/ena/ena.c
The API of the MODULE_PNP_INFO has changed in the FreeBSD 13.0 release.
It was MFCed to the stable/12 system, but stable/11 is still missing it.
This patch will also fix the compilation for the FreeBSD 12 release and
all 11.* releases and won't break anything for newer versions.
*Issue #, if available:* #111 
> fbsd/ena: fix MODULE_PNP_INFO call for FreeBSD 11

- kernel/fbsd/ena/Makefile
- kernel/fbsd/ena/README
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_com/ena_plat.h
- kernel/fbsd/ena/ena_datapath.c
- kernel/fbsd/ena/ena_datapath.h
- kernel/fbsd/ena/ena_netmap.c
- kernel/fbsd/ena/ena_netmap.h
Changes since last release (v2.0.0)
* Add netmap support.
* Add LLQ support for the aarch64 by enabling WC.
**Bug Fixes**
* Fix infinite missing keep alive reset loop in case the reset routine
takes too long because of the host being overloaded.
**Minor Changes**
* Split controller and datapath code into separate files.
> fbsd/ena: update ENA FreeBSD driver to v2.1.0

- kernel/fbsd/ena/README
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_datapath.c
Changes since last release (v2.1.0)
* Initialize cleanup task as NET_TASK - it is required by the latest
stack updates as NET_TASK is entering epoch mode upon execution.
**Bug Fixes**
* Fix race on multiple queues when LLQ is being enabled with Tx checksum
offload. It could lead to data corruption.
* Fix compilation for gcc by defining validate_rx_req_id() as
'static inline'.
> fbsd/ena: update ENA FreeBSD driver to v2.1.1

- kernel/fbsd/ena/Makefile
- kernel/fbsd/ena/README
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_com/ena_com.c
- kernel/fbsd/ena/ena_com/ena_com.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_admin_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_common_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_eth_io_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_gen_info.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_regs_defs.h
- kernel/fbsd/ena/ena_com/ena_eth_com.c
- kernel/fbsd/ena/ena_com/ena_eth_com.h
- kernel/fbsd/ena/ena_com/ena_plat.h
- kernel/fbsd/ena/ena_datapath.c
- kernel/fbsd/ena/ena_datapath.h
- kernel/fbsd/ena/ena_netmap.c
- kernel/fbsd/ena/ena_netmap.h
- kernel/fbsd/ena/ena_sysctl.c
- kernel/fbsd/ena/ena_sysctl.h
Changes since last release (v2.1.1)
* Add 'Tx drops' statistic which can be acquired by probing sysctl:
dev.ena.#.hw_stats.tx_drops
Where # stands for the interface number (0, 1, 2, ...).
* Mark the driver as epoch ready, to properly support latest FreeBSD 13
stack changes.
* Allow changing the number of IO queues during runtime by using sysctl:
dev.ena.#.io_queues_nb
Where # stands for the interface number (0, 1, 2, ...).
* Generate default RSS key using RNG in order to improve security.
**Bug Fixes**
* Fix ENA IO memory read/write macros - add appropriate barriers where
needed and remove them where they are no longer needed.
* Tx DMA mapping in case of the LLQ is being used was totally reworked
to improve stability and simplicity.
* Rx refill optimization for low memory …
> fbsd/ena: update ENA FreeBSD driver to v2.2.0

- userspace/dpdk/README.md
The new README file reworks the structure and contents of the previous
documentation making it more clear and adding missing information.
From the major changes, now it includes:
- More clear instructions for loading igb_uio and vfio-pci drivers
- Information about WC mapping
- Reworked instructions for applying the patches
- Section about static and runtime PMD configuration
> dpdk: rework documentation for the DPDK

- kernel/fbsd/ena/Makefile
- kernel/fbsd/ena/README
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_com/ena_com.c
- kernel/fbsd/ena/ena_com/ena_com.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_admin_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_common_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_eth_io_defs.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_gen_info.h
- kernel/fbsd/ena/ena_com/ena_defs/ena_regs_defs.h
- kernel/fbsd/ena/ena_com/ena_eth_com.c
- kernel/fbsd/ena/ena_com/ena_eth_com.h
- kernel/fbsd/ena/ena_com/ena_plat.h
- kernel/fbsd/ena/ena_datapath.c
- kernel/fbsd/ena/ena_datapath.h
- kernel/fbsd/ena/ena_netmap.c
- kernel/fbsd/ena/ena_netmap.h
- kernel/fbsd/ena/ena_sysctl.c
- kernel/fbsd/ena/ena_sysctl.h
Changes since last release (v2.2.0)
* Add ENI (Elastic Network Interface) metrics support. They can be
enabled and accessed using the sysctl.
* Add support for the Rx offsets (HW feature)
**Bug Fixes**
* Fix driver when running on kernel with RSS option being enabled
(please note, that the standalone driver should also be built with
'CFLAGS += -DRSS' option in the Makefile).
* Fix alignment of the ena_com_io_cq descriptors.
* Fix validation of the Rx requested ID.
**Minor Changes**
* Add SPDX license identifiers.
* Add description of all driver tunables to the README file.
* Fix names/description of the device IDs supported by the driver.
* Update HAL to the newer version.
* Remove deprecated ENA_WARN macro.
By submitting …
> fbsd/ena: update ENA FreeBSD driver to v2.3.0

- userspace/dpdk/RELEASENOTES.md
Add release notes like below:
* For main releases: v20.11
* For stable releases: v18.11.9
For v20.05, the ENA version was fixed - the r2.1.0 was released over
there, and not the r2.2.0.
r2.2.0 is part of the v20.11 release.
> dpdk/ena: update release notes up to v20.11

- userspace/dpdk/enav2-vfio-patch/get-vfio-with-wc.sh
The script is using 'tput' to change output color. Some virtual
terminals doesn't support those calls so tput will return an error.
Because of that, the error checking while configuring the terminal
colors was disabled.
Besides that, one missing 'exit' was added in the error handling path.
> dpdk: fix vfio install script for automation

- kernel/linux/ena/ena_netdev.c
This changes the default permission on all module paramers to 0444,
allowing the user to read the values that the module paramers are
set to.
Signed-off-by: Sargun Dhillon <sargun@sargun.me>
> ena: Make module params user readable

- kernel/fbsd/ena/README
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
Changes since last release (v2.3.0)
**Bug Fixes**
* Fix resource allocation if the MSIx vector table is not sharing the
BAR with the registers. FreeBSD requires all resources to be allocated
by the driver, so having unavailable BAR with MSIx vector table on it,
will prevent PCI code from allocating MSIx interrupts.
> fbsd/ena: update ENA FreeBSD driver to v2.3.1

- userspace/dpdk/RELEASENOTES.md
Add release notes for the listed DPDK versions:
* v21.05
* v21.02
* v20.11.1
* v19.11.7
* v19.11.6
* v18.11.11
Fix issues with invalid section placement for v18.02 and v17.02.
> dpdk/ena: update release notes up to v21.05

- kernel/linux/ena/ENA_Linux_Best_Practices.rst
*Issue #, if available:* N/A
Clarify `sysctl` commands for modifying `vm.min_free_kbytes` parameter.
> Fix vm.min_free_kbytes instructions in best practices

- kernel/fbsd/ena/README.rst
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_com/ena_plat.h
- kernel/fbsd/ena/ena_datapath.c
- kernel/fbsd/ena/ena_datapath.h
- kernel/fbsd/ena/ena_sysctl.c
Some of the changes in this release:
- IPv6 L4 checksum offload fixes.
- Optimization of the Tx req_id validatio
- Timer service adjustments.
- NUMA awareness for the kernel RSS mode.
> fbsd/ena: Update ENA driver to v2.5.0

- userspace/dpdk/RELEASENOTES.md
The release notes for v21.08 and v21.11 were missing. They are being updated in those patch series. Also release notes for the stable branches were updated.
> dpdk/ena: update release notes up to v21.11

- userspace/dpdk/README.md
Disabling LLQ may have negative impact on the performance especially
starting from the 6th generation platforms.
The ENA DPDK documentation was updated with the appropriate notice,
which highlights the impact of disabling the LLQ depending on the
used platform.
> dpdk/ena: add notice about LLQ and HW generations

- kernel/linux/ena/ENA_Linux_Best_Practices.rst
There was a missing whitespace that cause the code block missing. 
Original:
`.. code-block::bash`
Modified:
`.. code-block:: bash`
Add a whitespace to fix this issue.
> Fix the missing code block

- userspace/dpdk/README.md
*Issue #, if available:* #198, #216
*Description of changes:* Those commits updates the documentation to describe better the:
* Write Combining verification steps, which are common for both the `vfio-pci` and the `igb_uio`
* Extra notes regarding the `vfio-pci` and the latest Ubuntu kernel, which requires a workaround to fix the script which adds the WC support for the `vfio-pci`.
> dpdk/ena: Update documentation regarding kernel modules

- kernel/fbsd/ena/Makefile
- kernel/fbsd/ena/README.rst
- kernel/fbsd/ena/RELEASENOTES.md
- kernel/fbsd/ena/ena.c
- kernel/fbsd/ena/ena.h
- kernel/fbsd/ena/ena_datapath.c
- kernel/fbsd/ena/ena_datapath.h
- kernel/fbsd/ena/ena_netmap.c
- kernel/fbsd/ena/ena_netmap.h
- kernel/fbsd/ena/ena_rss.c
- kernel/fbsd/ena/ena_rss.h
- kernel/fbsd/ena/ena_sysctl.c
- kernel/fbsd/ena/ena_sysctl.h
Some of the changes in this release:
* Style fixes
* Fix ENI stats probing
* Add trace for the last Tx cleanup call
* Prevent LLQ initialization if member isn't exposed
* Improve logging
* Build system improvements
> fbsd/ena: Update driver version to v2.6.0

- userspace/dpdk/README.md
- userspace/dpdk/RELEASENOTES.md
This pull requests updates both the release notes and the ENA documentation 
due to the new ENA PMD release, which appeared in DPDK v22.03.
> dpdk/ena: Update docs after DPDK v22.03 release

- userspace/dpdk/enav2-vfio-patch/get-vfio-with-wc.sh
The 'apt' application is no longer able to download the kernel sources using the old way. The repository provides the package with meta-data instead of the sources. To download the sources directly, the 'unsigned-' string needs to be added to the 'linux-image-' package name.
*Issue #, if available:* #243
> dpdk/ena: Adjust vfio script to the apt behavior

- userspace/dpdk/enav2-vfio-patch/patches/linux-6.8-vfio-wc.patch
VFIO-PCI driver does not support write combine.
To activate this feature, the patch that checks
if PCI BAR is prefetchable must be added.
ubuntu 24.04 LTS keeps getting kernel updates which caused problem when applying ENA vfio patch.
*Issue #, if available:*
> dpdk: update WC patch for vfio for ubuntu lts
